### ISSUE TITLE
[Proposta] Enunciado dos exercícios

### ISSUE THREAD

**Issue by carusogabriel** [LeandroMontanari/python3-curso-em-video#1]
Olá @LeandroMontanari!

Primeiramente, parabéns pela iniciativa do repositório, achei bem bacana!

Queria dar uma idéia: poderíamos trabalhar em colocar os enunciados nos exercícios? Assim, gafanhotos que virão à consulta-los, saberão sobre o que o exercício se trata. Ex:
Exercício 001.py
```python
# Escreva um programa que imprima uma mensagem na tela
msg = 'Olá, Mundo!'
print(msg)
```

**Comment by LeandroMontanari** [comment]
Obrigado pela sugestão, @gabriel-caruso! Já inseri como comentário o título e o enunciado de cada exercício.
